### ISSUE TITLE
Bug occurred in log in page

### ISSUE THREAD

**Issue by mariaantonova** [pri6aleca321/brainmark.in#3]
Steps to reproduse:

Open page: http://brainmark.in/logIn/logIn.html
Find some unneaded symbols on the screen on the left.
![Uploading bug.png…]()
And see the attached screenshot of the error page.

**Comment by mariaantonova** [comment]
![bug](https://cloud.githubusercontent.com/assets/7831410/9132566/19c2f6fc-3cfd-11e5-8aa8-bfa4f8aade54.png)

**Comment by pri6aleca321** [comment]
Open the issue in order to fix it!
